### ISSUE TITLE
Please add `unit_of_measurement: ppb` to VOC

### ISSUE THREAD

**Issue by XScorpion2** [ApolloAutomation/AIR-1#11]
https://github.com/ApolloAutomation/AIR-1/blob/da6ab47e903d82da8b4f9b4bd37821580a10c5b2/Integrations/ESPHome/AIR-1.yaml#L205

This allows Home Assistant to perform unit conversions on the output.
Edit: Might want to add this field to all sensors just to ensure they are picked up correctly.

**Comment by Kars-de-Jong** [comment]
That would be incorrect. The VOC sensor uses Home Assistant device class `SensorDeviceClass.AQI`, which I believe to be correct. This class has no unit, see https://developers.home-assistant.io/docs/core/entity/sensor#available-device-classes.
The VOC measurement is an index with a baseline value of 100. See https://sensirion.com/media/documents/02232963/6294E043/Info_Note_VOC_Index.pdf for more information.

**Comment by XScorpion2** [comment]
Ah, thank you, didn't realize it was an index type. Much appreciated.
