### ISSUE TITLE
VOC configuration not ideal for indoor air quality monitoring

### ISSUE THREAD

**Issue by maia** [ApolloAutomation/AIR-1#13]
The currently used configuration of the sen55 voc sensor is not appropriate, based on the [Sensirion engineering guide](https://sensirion.com/media/documents/25AB572C/62B463AA/Sensirion_Engineering_Guidelines_SEN5x.pdf):

https://github.com/ApolloAutomation/AIR-1/blob/2739c8de5c000d03277375f3c2120584e1a6eed1/Integrations/ESPHome/AIR-1.yaml#L204-L213

E.g.: *"Learning Time Gain Hours: This parameter defines the range of the rolling window used by the algorithm to learn its gain from the history of sensor data. Due to the exponential decay function, sensor data older than twice the learning time become almost insignificant. The default value is 12 h. We recommend setting this parameter to the same value as “Learning Time Offset Hours”. In the case of indoor air quality monitoring, a time of 72h works optimal."*

I suggest changing `learning_time_offset_hours` and `learning_time_gain_hours` to 72 hours. I also wonder if `gating_max_duration_minutes` might need another value.

**Comment by TrevorSchirmer** [comment]
Thank you for the suggestion and finding that in the documentation. We've just updated the firmware.
