### ISSUE TITLE
Request firmware source code

### ISSUE THREAD

**Issue by tivold** [ApolloAutomation/AIR-1#16]
I'm considering purchasing an AIR-1.  Any chance I could get access to the actual source code for the firmware?  All I see is the compiled bin file, yaml config(s), and 3-D printer files.  Those are much appreciated, of course.

FWIW: Per the Sensirion documentation, if the logic board were mounted above the SEN55, with a bit of air-gap, you may very well need no default temperature offset.  Their docs specify that their temperature and humidity sensors ought to be below and/or thermally blocked from any other sources of heat, as much as practical.  That does pertain to the SEN55, as it does have both temperature and humidity sensors on board; and you do use those signals as the temperature and humidity outputs via the ESP - i.e. you don't include a distinct temperature/humitiy sensor.

Additionally, as one of the commenters on the wiki has already mentioned, the SEN55 inlet/outlet are not properly isolated, per Sensirion docs.  I intend to modify and post case model changes to fix that.

Here's links to the two Sensirion docs, respectively, in case you haven't found them.

https://sensirion.com/media/documents/FC5BED84/662B494D/Sensirion_Humidity_Temperature_Design_Guide.pdf
https://sensirion.com/media/documents/546FBC5B/61E9586E/Sensirion_Mechanical_Design_and_Assembly_Guidelines_SEN5x.pdf

Regards,
Tim

**Comment by TrevorSchirmer** [comment]
@tivold Thanks for dropping in. The YAML is actually the source for these devices. They use libraries in the ESPHome project but the YAML is all that is needed to run the sensor. The ESPHome project is also open source.

Yes, there is an air gap between the board and the SEN55, if you place the AIR-1 with the air vents facing up it'll have better thermals and be in the orientation you described. It can also go with vents down and some rubber feet are included.

Yes thanks for the tip on the SEN55 input / output. We were working on a case mod but got a little distracted. If you make an edit we'd love to see it!

Let us know if you need anything else!

Thanks,
Trevor
