### ISSUE TITLE
Can't update AIR-1 after ESPHome 2024.6.0 revision

### ISSUE THREAD

**Issue by Motya-HA** [ApolloAutomation/AIR-1#20]
[logs_living-room-air-quality-sensor_run.txt](https://github.com/user-attachments/files/16047853/logs_living-room-air-quality-sensor_run.txt)

INFO ESPHome 2024.6.4
INFO Reading configuration /config/esphome/living-room-air-quality-sensor.yaml...
WARNING GPIO9 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Generating C++ source...
INFO Compiling app...
Processing living-room-air-quality-sensor (board: esp32-c3-devkitm-1; framework: arduino; platform: platformio/espressif32@5.4.0)
HARDWARE: ESP32C3 160MHz, 320KB RAM, 4MB Flash
 - toolchain-riscv32-esp @ 8.4.0+2021r2-patch5
Dependency Graph
|-- AsyncTCP-esphome @ 2.1.3
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.2.2
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- Wire @ 2.0.0
|-- ArduinoJson @ 6.18.5
|-- noise-c @ 0.1.4
RAM:   [=         ]  11.4% (used 37260 bytes from 327680 bytes)
Flash: [======    ]  55.8% (used 1024746 bytes from 1835008 bytes)
========================= [SUCCESS] Took 17.48 seconds =========================
INFO Successfully compiled program.
INFO Connecting to 192.168.1.143
INFO Uploading /data/build/living-room-air-quality-sensor/.pioenvs/living-room-air-quality-sensor/firmware.bin (1039344 bytes)
ERROR ESP requests password, but no password given!

**Comment by TrevorSchirmer** [comment]
Hello @Motya-HA ,

Are you still having the issue updating? It looks like it is missing the OTA password, if you edit the YAML in ESPHome addon it should look like this:

`ota:
  - platform: esphome
    password: "apolloautomation"
`
