### ISSUE TITLE
ESPHome 2024.9.1 CO and NO2 values incorrect

### ISSUE THREAD

**Issue by haroldboom** [ApolloAutomation/AIR-1#37]
After I updated my ESPHome to 2024.9.1 the values for my CO and NO2 seem to be incorrect. CO never goes lower than ~4ppm even when the AIR-1 is outside and NO2 fluctuates between 0.16 and 0.17ppm. Before the update they were always 0. See below.

![image](https://github.com/user-attachments/assets/d0e20d9d-9da0-4b06-b105-aed30052e55d)
![image](https://github.com/user-attachments/assets/e266f2d9-45a8-48fc-920f-18ed5f93f20b)

Also my house is all electric, we have no gas or fire place etc.

**Comment by TrevorSchirmer** [comment]
Hello, the update in ESPHome was an improvement to the sensor range on the MiCS-4514 particularly the lower end. The MiCS code in ESPHome was ignoring lower values and reporting them as zero. An AIR-1 user figured this out based on the MiCS documentation and a fix was put into ESPHome to help with lower ppm readings. 

From what I can find a CO level of 4ppm is perfectly normal in outdoor air so there should be no concern there.

There are still some bugs in the MiCS readings that some users are talking about in the ESPHome GitHub around making sure it is reading the correct values for the full range.

**Comment by haroldboom** [comment]
Oh awesome so it’s now showing the real levels. Thanks for the reply mate,
I love my AIR-1!

**Comment by TrevorSchirmer** [comment]
Of course. Thanks for letting us know, we appreciate it!
