### ISSUE TITLE
Weekly crashes on 24.7.15.1

### ISSUE THREAD

**Issue by robd003** [ApolloAutomation/AIR-1#38]
I've noticed that with the latest update `24.7.15.1` that the AIR-1 will reboot at least once a week. All previous releases were very stable in comparison.

Is there any good way to debug what is going on @TrevorSchirmer ?

![Screenshot 2024-10-01 at 1 46 55 PM](https://github.com/user-attachments/assets/7138606f-a580-4136-97fc-a2901cd6351d)

Before anyone says power outages, the AIR-1 is connected to a UPS.

**Comment by TrevorSchirmer** [comment]
Being at about the same time is odd for sure. We've seen this before with Ubiquiti setups where they restart the internet in the early morning. 4pm wouldn't fit that though.

That firmware came out in mid July and this is the first we've heard of it. Did it recently start happening? Or did you just recently update the firmware?

Thanks for helping.

-Trevor

**Comment by robd003** [comment]
@TrevorSchirmer I just recently updated the firmware.

It's gotten a LOT worse now:
<img width="1447" alt="Screenshot 2024-10-02 at 4 46 39 PM" src="https://github.com/user-attachments/assets/c53160ff-707b-4eda-a92d-e6555e3f59be">

**Comment by TrevorSchirmer** [comment]
@robd003 Really apologize for this slipping. Were you able to get help from us in discord or support email or are you still having issues?

**Comment by robd003** [comment]
@TrevorSchirmer Was sent a replacement board and it's been working great. Currently running firmware `24.7.15.1` which was build on ESPHome 2024.9.1

Is it worth updating to the latest build? (24.10.11.1)
