### ISSUE TITLE
Firmware binary too big to update

### ISSUE THREAD

**Issue by yieldhog** [ApolloAutomation/AIR-1#8]
On ESPHome 2024.3.0, I can no longer update due to the size of the binary file. Have not had this issue in the past.

Encryption disabled:
INFO Uploading /data/build/apollo-air-1-bb7df0/.pioenvs/apollo-air-1-bb7df0/firmware.bin (1849232 bytes)
ERROR Error binary size: Error: The OTA partition on the ESP is too small. ESPHome needs to resize this partition, please flash over USB.

Encryption enabled:
RAM:   [==        ]  17.6% (used 57652 bytes from 327680 bytes)
Flash: [==========]  101.3% (used 1858414 bytes from 1835008 bytes)
Error: The program size (1858414 bytes) is greater than maximum allowed (1835008 bytes)
*** [checkprogsize] Explicit exit, status 1

--
Configuration:

substitutions:
  name: apollo-air-1-bb7df0
  friendly_name: Apollo AIR
packages:
  ApolloAutomation.AIR-1: github://ApolloAutomation/AIR-1/Integrations/ESPHome/AIR-1.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: [redacted]
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

**Comment by tybo611** [comment]
Same error.

**Comment by jphoke** [comment]
Confirming this OTA update error on current ESPHome in HA (2024.3.0) ... will pull one down and see if it works via USB later this evening and comment.

**Comment by TrevorSchirmer** [comment]
Thanks all, I just merged some changes that greatly reduced the firmware size. It'll take about a day for it to refresh on the ESPHome side for us to try out.

**Comment by yieldhog** [comment]
Worked for me, thanks!

**Comment by selfjc** [comment]
I am now having this issue with ESPHome 2024.6.6. I see the esp32-c3-devkit board has 4MB of flash more than the ~1.8MB that ESPHome (this yaml script) uses. 

Do we just try to let ESPHome resize the partition or did something grow too large from 2024.6.4?

**Comment by TrevorSchirmer** [comment]
@selfjc Thanks for dropping in.

Yes they have 4MB of flash, but with an OTA update we can only use half of it.

We added some components to qualify for the "Made For ESPHome" program and it pushed firmware up a few % over the max.

Late last night I reremoved the logger from the AIR-1 to get back a few % and it should compile fine now.

I'm assuming you are running BLE proxy or BLE tracking? Those are the only ones that saw the firmware size restriction.



It should take about 24 hours for ESPHome's cache to clear and for you to be able to compile the smaller firmware and update.

Thanks,
Trevor

**Comment by selfjc** [comment]
No sir, I am not using the Bluetooth proxy. I am running the Air-1 vanilla with the following added so that it connects to my hidden wifi SSID:

wifi:
  # Use fast_connect for hidden wifi SSID
  fast_connect: true
  ssid: !secret wifi_ssid
  password: !secret wifi_password

text_sensor:
  - platform: wifi_info
    ip_address: 
      name: "IP Address"
      icon: "mdi:ip-outline"
    mac_address: 
      name: "Mac Wifi Address"
      icon: "mdi:ip-outline"

**Comment by selfjc** [comment]
The cache updated faster than anticipated as the firmware now only uses ~65% of the available flash. Thanks for the quick update!
